import { index, route } from "@react-router/dev/routes";

export default [
  route("", "routes/main-shell.jsx", [
    index("routes/home.jsx"),
    route("search", "routes/search.jsx"),
    route("discover", "routes/discover-layout.jsx", [
      index("routes/discover._index.jsx"),
      route("happening-now", "routes/discover.happening-now.jsx"),
      route("upcoming", "routes/discover.upcoming.jsx"),
      route("places", "routes/discover.places.jsx"),
      route("event/:id", "routes/discover.event.$id.jsx"),
      route("place/:id", "routes/discover.place.$id.jsx"),
    ]),
    route("profile", "routes/account-layout.profile.jsx", [
      index("routes/profile.jsx"),
      route("settings", "routes/profile.settings.jsx"),
      route("settings/account", "routes/profile.settings.account.jsx"),
      route("settings/change-password", "routes/profile.settings.change-password.jsx"),
      route("settings/change-email", "routes/profile.settings.change-email.jsx"),
      route("settings/language", "routes/profile.settings.language.jsx"),
      route("settings/privacy", "routes/profile.settings.privacy.jsx"),
      route("settings/feedback", "routes/profile.settings.feedback.jsx"),
      route("memos", "routes/profile.memos.jsx"),
      route("memos/:id/edit", "routes/profile.memos.$id.edit.jsx"),
      route("favourites", "routes/profile.favourites-layout.jsx", [
        index("routes/profile.favourites._index.jsx"),
        route("memos", "routes/profile.favourites.memos.jsx"),
        route("spots", "routes/profile.favourites.spots.jsx"),
        route("events", "routes/profile.favourites.events.jsx"),
      ]),
    ]),
    route("journals", "routes/journals.jsx"),
    route("journals/create", "routes/journals.create.jsx"),
    route("journals/create/memos", "routes/journals.create.memos.jsx"),
    route("journals/:id/edit", "routes/journals.$id.edit.jsx"),
    route("journals/:id/edit/memos", "routes/journals.$id.edit.memos.jsx"),
  ]),
  route("login", "routes/login.jsx"),
  route("forgot-password", "routes/forgot-password.jsx"),
  route("reset-password", "routes/reset-password.jsx"),
  route("register", "routes/register.jsx"),
  route("stickers", "routes/account-layout.stickers.jsx", [
    index("routes/stickers.jsx"),
  ]),
  route("collect", "routes/collect.jsx"),
  route("connect", "routes/connect.jsx"),
  route("demo-stickers", "routes/demo-stickers.jsx"),
  route("diary/:id", "routes/diary.$id.jsx"),
  route("location/:osmType/:osmId/memos", "routes/location.$osmType.$osmId.memos.jsx"),
  route("location/:osmType/:osmId", "routes/location.$osmType.$osmId.jsx"),
  route("api/stickers", "routes/api.stickers.js"),
  route("api/memos", "routes/api.memos.js"),
  route("api/account", "routes/api.account.js"),
  route("api/reset-password", "routes/api.reset-password.js"),
  route("api/feedback", "routes/api.feedback.js"),
  route("api/location-search", "routes/api.location-search.js"),
  route("api/location-href", "routes/api.location-href.js"),
  route("*", "routes/catchall.jsx"),
];
